### ISSUE TITLE
Job status will change form `FINISHED` to `FAILED`

### ISSUE THREAD

**Issue by dl239** [4paradigm/OpenMLDB#1104]
![d3f919c538af62935eaef4448fa8d37b](https://user-images.githubusercontent.com/6183996/149605463-cb7c3cf3-185e-43ff-8023-01ae14f542ca.png)

**Comment by tobegit3hub** [comment]
@dl239 Could you provide the steps to reproduce the issue? Use the demo docker images or other environment?

**Comment by lumianph** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)

**Comment by tobegit3hub** [comment]
Here is the error log of TaskManager job.

```
22/02/21 04:35:50 INFO LoadDataPlan$: read schema: StructType(StructField(c1,StringType,true), StructField(c2,IntegerType,true), StructFi
eld(c3,LongType,true), StructField(c4,FloatType,true), StructField(c5,DoubleType,true), StructField(c6,TimestampType,true), StructField(c
7,DateType,true))
Exception in thread "main" org.apache.spark.sql.AnalysisException: Path does not exist: file:/work/taxi-trip/data/data.parquet;
        at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:759)
        at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
        at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
        at scala.collection.immutable.List.flatMap(List.scala:355)
        at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:746)
        at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:575)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:398)
        at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:279)
        at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:268)
        at scala.Option.getOrElse(Option.scala:189)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:268)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:214)
        at com._4paradigm.openmldb.batch.nodes.LoadDataPlan$.gen(LoadDataPlan.scala:125)
        at com._4paradigm.openmldb.batch.SparkPlanner.visitNode(SparkPlanner.scala:266)
        at com._4paradigm.openmldb.batch.SparkPlanner.getSparkOutput(SparkPlanner.scala:229)
        at com._4paradigm.openmldb.batch.SparkPlanner.$anonfun$plan$1(SparkPlanner.scala:110)
        at com._4paradigm.openmldb.batch.SparkPlanner.withSQLEngine(SparkPlanner.scala:340)
        at com._4paradigm.openmldb.batch.SparkPlanner.plan(SparkPlanner.scala:80)
        at com._4paradigm.openmldb.batch.api.OpenmldbSession.openmldbSql(OpenmldbSession.scala:156)
        at com._4paradigm.openmldb.batch.api.OpenmldbSession.sql(OpenmldbSession.scala:167)
        at com._4paradigm.openmldb.batchjob.ImportOfflineData$.importOfflineData(ImportOfflineData.scala:34)
        at com._4paradigm.openmldb.batchjob.ImportOfflineData$.main(ImportOfflineData.scala:29)
        at com._4paradigm.openmldb.batchjob.ImportOfflineData.main(ImportOfflineData.scala)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
```

And the parquet of `/work/taxi-trip/data/data.parquet` does not exist. The docker has file `/work/taxi-trip/data/taxi_tour_table_train_simple.snappy.parquet`.

**Comment by tobegit3hub** [comment]
This happens if the job fails and the final state `FAILED` is correct. Sometimes users run offline job without downing `data.parquet` will get this error.

**Comment by tobegit3hub** [comment]
If it's yarn job, we could get the final state from yarn client API. But for local job, we can only get the state from Spark handler which will change `FINISHED` to `FAILED` for failed jobs.

Close and won't fix.
