### ISSUE TITLE
openmldbspark webui get static resource failed

### ISSUE THREAD

**Issue by zoyopei** [4paradigm/OpenMLDB#1183]
OS: ubuntu18.04, Spark run in standalone mode.
WebUI:
<img width="964" alt="webui" src="https://user-images.githubusercontent.com/14039925/153351648-63604e2c-96c7-43a1-9f2f-b3f3491cfb2c.png">

Master log:
```
22/02/10 06:36:58 WARN HttpChannel: /static/timeline-view.css
java.lang.NoSuchMethodError: 'boolean javax.servlet.http.HttpServletRequest.isAsyncSupported()'
        at org.sparkproject.jetty.server.ResourceService.sendData(ResourceService.java:697)
        at org.sparkproject.jetty.server.ResourceService.doGet(ResourceService.java:294)
        at org.sparkproject.jetty.servlet.DefaultServlet.doGet(DefaultServlet.java:457)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
        at org.sparkproject.jetty.servlet.ServletHolder.handle(ServletHolder.java:873)
        at org.sparkproject.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1623)
        at org.apache.spark.ui.HttpSecurityFilter.doFilter(HttpSecurityFilter.scala:95)
        at org.sparkproject.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1610)
        at org.sparkproject.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:540)
        at org.sparkproject.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
        at org.sparkproject.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1345)
        at org.sparkproject.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
        at org.sparkproject.jetty.servlet.ServletHandler.doScope(ServletHandler.java:480)
        at org.sparkproject.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
        at org.sparkproject.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1247)
        at org.sparkproject.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.sparkproject.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:753)
        at org.sparkproject.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:220)
        at org.sparkproject.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.sparkproject.jetty.server.Server.handle(Server.java:505)
        at org.sparkproject.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.sparkproject.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.sparkproject.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.sparkproject.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.sparkproject.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
        at org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
        at org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
        at org.sparkproject.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:132)
        at org.sparkproject.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.sparkproject.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.base/java.lang.Thread.run(Unknown Source)
```

I found an old version of javax.servlet.ServletRequest in openmldb-batch-0.4.0.jar. When I remove the servlet package from openmldb-batch-0.4.0.jar, the webui is ok.

**Comment by tobegit3hub** [comment]
Thanks @zoyopei . We may exclude the `javax.servlet.ServletRequest` in openmldb-batch and use the one in Spark dependencies. 

It is welcome to send pull-request to fix it.

**Comment by tobegit3hub** [comment]
Resolved.
