### ISSUE TITLE
Compile error when register empty dataframe in offline mode

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1300]
Here is the SQL to create test tables.

```
create table test_lastjoin01(
    id int,
    c1 string,
    c6 timestamp,
    c7 timestamp,
    c8 date,
    index(key=c1,ts=c6,ttl=0m,ttl_type=absolute)
)options(partitionnum = 1,replicanum = 1);
```

```
create table test_lastjoin02(
    id int,
    c1 string,
    c6 timestamp,
    c7 timestamp,
    c8 date,
    index(key=c1,ts=c6,ttl=0m,ttl_type=absolute)
)options(partitionnum = 1,replicanum = 1);
```

Here is the query SQL.

```
SET @@SESSION.execute_mode = "offline";

SELECT test_lastjoin01.id as id01,  test_lastjoin02.id as id02,  test_lastjoin01.c7 as c71,   test_lastjoin02.c7 as c72  FROM test_lastjoin01 last join test_lastjoin02  order by  test_lastjoin02.c6 on test_lastjoin01.c7=test_lastjoin02.c7;
```

And we get the error message in offline mode.

```
22/02/24 11:02:42 INFO OpenmldbSession: Register empty dataframe fof db1.score
22/02/24 11:02:42 INFO OpenmldbSession: Register empty dataframe fof db1.user
22/02/24 11:02:42 INFO OpenmldbSession: Register empty dataframe fof db2.t1
22/02/24 11:02:42 INFO OpenmldbSession: Register empty dataframe fof qatest.test_lastjoin01
22/02/24 11:02:42 INFO OpenmldbSession: Register empty dataframe fof qatest.test_lastjoin02
22/02/24 11:02:42 INFO SparkPlanner: Disable window parallelization optimization, enable by setting openmldb.window.parallelization
Exception in thread "main" com._4paradigm.hybridse.sdk.UnsupportedHybridSeException: SQL parse error: Column Not found: .test_lastjoin02.c6
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/sql_compiler.cc:263)
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/sql_compiler.cc:166)
    (Caused by) Fail to generate physical plan batch mode
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/transform.cc:1672)
    (Caused by) Fail to transform query statement
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/transform.cc:103)
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/transform.cc:413)
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/transform.cc:108)
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/transform.cc:759)
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/transform.cc:1924)
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/schemas_context.cc:258)
    (Caused by) Fail to resolve column .test_lastjoin02.c6
    (At /Users/tobe/code/4pd/openmlDB/hybridse/src/vm/schemas_context.cc:679)
    (Caused by) Column Not found: .test_lastjoin02.c6

	at com._4paradigm.hybridse.sdk.SqlEngine.initilize(SqlEngine.java:130)
	at com._4paradigm.hybridse.sdk.SqlEngine.<init>(SqlEngine.java:88)
	at com._4paradigm.openmldb.batch.SparkPlanner.withSQLEngine(SparkPlanner.scala:339)
	at com._4paradigm.openmldb.batch.SparkPlanner.plan(SparkPlanner.scala:80)
	at com._4paradigm.openmldb.batch.api.OpenmldbSession.openmldbSql(OpenmldbSession.scala:157)
	at com._4paradigm.openmldb.batch.api.OpenmldbSession.sql(OpenmldbSession.scala:168)
	at com._4paradigm.openmldb.batchjob.RunBatchAndShow$.runBatchSql(RunBatchAndShow.scala:34)
	at com._4paradigm.openmldb.batchjob.RunBatchAndShow$.main(RunBatchAndShow.scala:29)
	at com._4paradigm.openmldb.batchjob.RunBatchAndShow.main(RunBatchAndShow.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
	at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:928)
	at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:180)
	at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:203)
	at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:90)
	at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1007)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1016)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

**Comment by tobegit3hub** [comment]
It happens when the offline data is not imported and we create the empty dataframe without schema.
