### ISSUE TITLE
duplicate static library link

### ISSUE THREAD

**Issue by zhanghaohit** [4paradigm/OpenMLDB#1385]
## Expected Behavior
static lib should be linked only one time.

## Current Behavior
Some static libs are linked multiple times.
in [`src/sdk/CMakeLists.txt`](https://github.com/4paradigm/OpenMLDB/blob/2f85d12cd8dadd3a1ec822e1f591632341f3b23f/src/sdk/CMakeLists.txt#L52)

`set(SDK_LIBS openmldb_sdk openmldb_catalog client zk_client schema openmldb_flags openmldb_codec openmldb_proto base hybridse_sdk zookeeper_mt ${VM_LIBS} ${LLVM_LIBS} ${BRPC_LIBS} ${ZETASQL_LIBS}) `

where `${VM_LIBS} ${LLVM_LIBS} ${BRPC_LIBS} ${ZETASQL_LIBS} ` are not necessary and already linked by `hybridse_sdk`.

It may cause unexpected fault if we link multiple times. see [here](https://github.com/4paradigm/OpenMLDB/runs/5425348767?check_suite_focus=true)

## Possible Solution

It is not obvious what will happen if we link a static lib multiple times. We have to figure it out what are the correct way to do this. 

I believe there are other places where there are duplicate links except the `SDK_LIBS`. But it for now does not trigger any error or unexpected crash.

**Comment by aceforeverd** [comment]
So it's runtime fault not link time? What the error will be like? E.g.

**Comment by aceforeverd** [comment]
See if similar with #752, it only happen in Release profile

**Comment by zhanghaohit** [comment]
> So it's runtime fault not link time? What the error will be like? E.g.

Yes. It is runtime fault. The error message is not very helpful:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M5:test (default-test) on project openmldb-jdbc: There are test failures.
Error:  
Error:  Please refer to /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error:  ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc && /__t/Java_Adopt_jdk/8.0.322-6/x64/jre/bin/java -javaagent:/github/home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/jacoco.exec -Xmx4G -jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire/surefirebooter3256724465573143702.jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire 2022-03-04T16-59-55_073-jvmRun1 surefire6588409757678444010tmp surefire_36192990973336427768tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 127
Error:  ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc && /__t/Java_Adopt_jdk/8.0.322-6/x64/jre/bin/java -javaagent:/github/home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/jacoco.exec -Xmx4G -jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire/surefirebooter4424262036073269994.jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire 2022-03-04T16-59-55_073-jvmRun1 surefire7722056936772452260tmp surefire_56823541840772590674tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 127
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc && /__t/Java_Adopt_jdk/8.0.322-6/x64/jre/bin/java -javaagent:/github/home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/jacoco.exec -Xmx4G -jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire/surefirebooter3256724465573143702.jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire 2022-03-04T16-59-55_073-jvmRun1 surefire6588409757678444010tmp surefire_36192990973336427768tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 127
Error:  ExecutionException The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc && /__t/Java_Adopt_jdk/8.0.322-6/x64/jre/bin/java -javaagent:/github/home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/jacoco.exec -Xmx4G -jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire/surefirebooter4424262036073269994.jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire 2022-03-04T16-59-55_073-jvmRun1 surefire7722056936772452260tmp surefire_56823541840772590674tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 127
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.awaitResultsDone(ForkStarter.java:532)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.runSuitesForkPerTestSet(ForkStarter.java:479)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:322)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:266)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1314)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1159)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:932)
Error:  	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
Error:  	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
Error:  	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
Error:  	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:[305](https://github.com/4paradigm/OpenMLDB/runs/5425348767?check_suite_focus=true#step:11:305))
Error:  	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
Error:  	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
Error:  	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
Error:  	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
Error:  	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
Error:  	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.lang.reflect.Method.invoke(Method.java:498)
Error:  	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
Error:  	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
Error:  	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
Error:  Caused by: org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Error:  Command was /bin/sh -c cd /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc && /__t/Java_Adopt_jdk/8.0.[322](https://github.com/4paradigm/OpenMLDB/runs/5425348767?check_suite_focus=true#step:11:322)-6/x64/jre/bin/java -javaagent:/github/home/.m2/repository/org/jacoco/org.jacoco.agent/0.8.7/org.jacoco.agent-0.8.7-runtime.jar=destfile=/__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/jacoco.exec -Xmx4G -jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire/surefirebooter442426203607[326](https://github.com/4paradigm/OpenMLDB/runs/5425348767?check_suite_focus=true#step:11:326)9994.jar /__w/OpenMLDB/OpenMLDB/java/openmldb-jdbc/target/surefire 2022-03-04T16-59-55_073-jvmRun1 surefire7722056936772452260tmp surefire_5682[354](https://github.com/4paradigm/OpenMLDB/runs/5425348767?check_suite_focus=true#step:11:354)1840772590674tmp
Error:  Error occurred in starting fork, check output in log
Error:  Process Exit Code: 127
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:748)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.access$700(ForkStarter.java:121)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:465)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter$2.call(ForkStarter.java:442)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Error:  	at java.lang.Thread.run(Thread.java:750)
Error:  -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
Error:  
Error:  After correcting the problems, you can resume the build with the command
Error:    mvn <args> -rf :openmldb-jdbc
Error: Process completed with exit code 1.
```

The environment can be see here: https://github.com/4paradigm/OpenMLDB/runs/5425348767?check_suite_focus=true

**Comment by zhanghaohit** [comment]
> 

`Release profile` you mean
-DCMAKE_BUILD_TYPE=RelWithDebInfo?

These two issues may be related.  In #752, only moving the function definition to the cc files will help?

**Comment by aceforeverd** [comment]
> > 
> 
> `Release profile` you mean -DCMAKE_BUILD_TYPE=RelWithDebInfo?
> 
> These two issues may be related. In #752, only moving the function definition to the cc files will help?

it's `-DCMAKE_BUILD_TYPE=Release`, in #752 compile will fail in Release profile, since our workflows do not run on Release, there might errors we don't found yet. As @vagetablechicken said at https://github.com/4paradigm/OpenMLDB/issues/748#issuecomment-973944703

But this issue occur on runtime, more wired

**Comment by aceforeverd** [comment]
the binary won't run if dynamic link `hybridse_sdk` and `hybridse_core`, so I removed `VM_LIBS` in #1864 
does other libs can be removed even for dynamic linking @zhanghaohit ?

**Comment by zhanghaohit** [comment]
> 

not really sure. we may have to try and test what are the really needed libraries.

**Comment by aceforeverd** [comment]
another related problem: #1932 
gflags is linked multiple times from like `hybridse_flags`, `openmldb_flags` or `toydb_flags`, this may work in static link but not allowed in dynamic link.
