### ISSUE TITLE
Get unexpected long overflow for offline job when enabling UnsafeRowOpt 

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1632]
**Bug Description**

Here is the test SQL.

```
select * from
(
select
    reqId as reqId_1,
    `reqId` as flattenRequest_reqId_original_0,
    `eventTime` as flattenRequest_eventTime_original_1,
    `f_requestId` as flattenRequest_f_requestId_original_2,
    `f_cId` as flattenRequest_f_cId_original_3,
    `f_cType` as flattenRequest_f_cType_original_4,
    `f_cTitle` as flattenRequest_f_cTitle_5,
    `f_cKey` as flattenRequest_f_cKey_6,
    `f_cLabel` as flattenRequest_f_cLabel_7,
    `f_cSrc` as flattenRequest_f_cSrc_original_8,
    `f_cPubTime` as flattenRequest_f_cPubTime_original_9,
    `f_cLength` as flattenRequest_f_cLength_original_10,
    `f_cReader` as flattenRequest_f_cReader_original_11,
    `f_cSex` as flattenRequest_f_cSex_original_12,
    `f_cPro` as flattenRequest_f_cPro_original_13,
    `f_cAge` as flattenRequest_f_cAge_original_14,
    `f_cLike` as flattenRequest_f_cLike_original_15,
    `f_cDislike` as flattenRequest_f_cDislike_original_16,
    `f_uId` as flattenRequest_f_uId_original_17,
    `f_uSex` as flattenRequest_f_uSex_original_18,
    `f_uPay` as flattenRequest_f_uPay_original_19,
    `f_uSub` as flattenRequest_f_uSub_original_20,
    `f_uRegTime` as flattenRequest_f_uRegTime_original_21,
    `f_uLikeLabel` as flattenRequest_f_uLikeLabel_22,
    `f_uLikeSrc` as flattenRequest_f_uLikeSrc_23,
    `f_uLikeKey` as flattenRequest_f_uLikeKey_24,
    `f_uDisLikeLabel` as flattenRequest_f_uDisLikeLabel_25,
    `f_uDislikeSrc` as flattenRequest_f_uDislikeSrc_original_26,
    `f_uDislikeKey` as flattenRequest_f_uDislikeKey_27,
    `f_pRank` as flattenRequest_f_pRank_original_28,
    `f_pCount` as flattenRequest_f_pCount_original_29,
    `f_UUID` as flattenRequest_f_UUID_original_30,
    sum(`f_cLength`) over flattenRequest_f_requestId_eventTime_0s_604801s_100 as flattenRequest_f_cLength_window_sum_32,
    `f_uId` as flattenRequest_f_uId_combine_33,
    `f_uId` as flattenRequest_f_uId_combine_34,
    `f_cType` as flattenRequest_f_cType_combine_35,
    `f_uId` as flattenRequest_f_uId_combine_35,
    `f_uDislikeSrc` as flattenRequest_f_uDislikeSrc_combine_35,
    `f_uId` as flattenRequest_f_uId_combine_36,
    `f_uSex` as flattenRequest_f_uSex_combine_36,
    `f_uDislikeSrc` as flattenRequest_f_uDislikeSrc_combine_36,
    `f_uId` as flattenRequest_f_uId_combine_37,
    `f_uSex` as flattenRequest_f_uSex_combine_37,
    `f_uPay` as flattenRequest_f_uPay_combine_37,
    distinct_count(`f_cId`) over flattenRequest_f_uId_eventTime_0_10_ as flattenRequest_f_cId_window_unique_count_38,
    fz_top1_ratio(`f_cId`) over flattenRequest_f_requestId_eventTime_0_10_ as flattenRequest_f_cId_window_top1_ratio_39,
    fz_top1_ratio(`f_cId`) over flattenRequest_f_requestId_eventTime_0s_604801s_100 as flattenRequest_f_cId_window_top1_ratio_40,
    sum(`f_cLength`) over flattenRequest_f_requestId_eventTime_0s_432001s_100 as flattenRequest_f_cLength_window_sum_41,
    case when !isnull(at(`f_cSrc`, 0)) over flattenRequest_f_requestId_eventTime_0s_604801s_100 then count(`f_cSrc`) over flattenRequest_f_requestId_eventTime_0s_604801s_100 else null end as flattenRequest_f_cSrc_window_count_42,
    case when !isnull(at(`f_cSrc`, 0)) over flattenRequest_f_uId_eventTime_0s_604801s_100 then count(`f_cSrc`) over flattenRequest_f_uId_eventTime_0s_604801s_100 else null end as flattenRequest_f_cSrc_window_count_43,
    fz_top1_ratio(`f_cId`) over flattenRequest_f_uId_eventTime_0_10_ as flattenRequest_f_cId_window_top1_ratio_44,
    fz_top1_ratio(`f_cId`) over flattenRequest_f_uId_eventTime_0s_604801s_100 as flattenRequest_f_cId_window_top1_ratio_45,
    fz_top1_ratio(`f_cId`) over flattenRequest_f_uId_eventTime_0s_432001s_100 as flattenRequest_f_cId_window_top1_ratio_46,
    case when !isnull(at(`f_cId`, 0)) over flattenRequest_f_requestId_eventTime_0s_604801s_100 then count(`f_cId`) over flattenRequest_f_requestId_eventTime_0s_604801s_100 else null end as flattenRequest_f_cId_window_count_47,
    case when !isnull(at(`f_cId`, 0)) over flattenRequest_f_uId_eventTime_0s_432001s_100 then count(`f_cId`) over flattenRequest_f_uId_eventTime_0s_432001s_100 else null end as flattenRequest_f_cId_window_count_48,
    case when !isnull(at(`f_cId`, 0)) over flattenRequest_f_uId_eventTime_0s_604801s_100 then count(`f_cId`) over flattenRequest_f_uId_eventTime_0s_604801s_100 else null end as flattenRequest_f_cId_window_count_49
from
    `flattenRequest`
    window flattenRequest_f_requestId_eventTime_0s_604801s_100 as (partition by `f_requestId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding MAXSIZE 100),
    flattenRequest_f_uId_eventTime_0_10_ as (partition by `f_uId` order by `eventTime` rows between 9 preceding and 0 preceding),
    flattenRequest_f_requestId_eventTime_0_10_ as (partition by `f_requestId` order by `eventTime` rows between 9 preceding and 0 preceding),
    flattenRequest_f_requestId_eventTime_0s_432001s_100 as (partition by `f_requestId` order by `eventTime` rows_range between 432000999 preceding and 0s preceding MAXSIZE 100),
    flattenRequest_f_uId_eventTime_0s_604801s_100 as (partition by `f_uId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding MAXSIZE 100),
    flattenRequest_f_uId_eventTime_0s_432001s_100 as (partition by `f_uId` order by `eventTime` rows_range between 432000999 preceding and 0s preceding MAXSIZE 100))
as out0
last join
(
select
    flattenRequest.reqId as reqId_32,
    `action_reqId`.`actionValue` as action_actionValue_multi_direct_31
from
    `flattenRequest`
    last join `action` as `action_reqId` on `flattenRequest`.`reqId` = `action_reqId`.`reqId`)
as out1
on out0.reqId_1 = out1.reqId_32;
```

And we will get the exception like this.

```
java.lang.RuntimeException: Error while encoding: java.lang.ArithmeticException: long overflow
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:215)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:197)
	at scala.collection.Iterator$$anon$10.next(Iterator.scala:459)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:132)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ArithmeticException: long overflow
	at java.lang.Math.multiplyExact(Math.java:892)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.fromMillis(DateTimeUtils.scala:225)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils$.fromJavaTimestamp(DateTimeUtils.scala:182)
	at org.apache.spark.sql.catalyst.util.DateTimeUtils.fromJavaTimestamp(DateTimeUtils.scala)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.StaticInvoke_17$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.writeFields_0_9$(Unknown Source)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificUnsafeProjection.apply(Unknown Source)
	at org.apache.spark.sql.catalyst.encoders.ExpressionEncoder$Serializer.apply(ExpressionEncoder.scala:211)
	... 17 more
```

Here is the debug info when we try to access the internal object.

<img width="724" alt="Screen Shot 2022-04-15 at 10 50 05 AM" src="https://user-images.githubusercontent.com/2715000/163511984-998970c4-3825-4f7f-9c98-3f9b91a4f26a.png">

**Comment by tobegit3hub** [comment]
Simplify the test case to reproduce the issue.

Here is the input data.

```
+--------------------+-----+--------------------+--------+-------------------+-------------------+
|               reqId|f_cId|         f_requestId|   f_uId|          eventTime|         f_cPubTime|
+--------------------+-----+--------------------+--------+-------------------+-------------------+
|af5a2911-cb66-11e...| 3758|5844c0f6ae41d1772...|19403095|2016-12-05 08:00:00|2016-10-08 08:00:00|
|a2099338-cb66-11e...|  113|584c857a7ab100483...|11198457|2016-12-11 08:00:00|2015-11-17 08:00:00|
|99ed84ab-cb66-11e...| 1369|584ce64261d046451...|  699873|2016-12-11 08:00:00|2016-04-29 08:00:00|
+--------------------+-----+--------------------+--------+-------------------+-------------------+

{
  "type" : "struct",
  "fields" : [ {
    "name" : "reqId",
    "type" : "string",
    "nullable" : true,
    "metadata" : { }
  }, {
    "name" : "f_cId",
    "type" : "string",
    "nullable" : true,
    "metadata" : { }
  }, {
    "name" : "f_requestId",
    "type" : "string",
    "nullable" : true,
    "metadata" : { }
  }, {
    "name" : "f_uId",
    "type" : "string",
    "nullable" : true,
    "metadata" : { }
  }, {
    "name" : "eventTime",
    "type" : "timestamp",
    "nullable" : true,
    "metadata" : { }
  }, {
    "name" : "f_cPubTime",
    "type" : "timestamp",
    "nullable" : true,
    "metadata" : { }
  } ]
}
```

Here is the SQL.

```
select
    count(`f_cId`) over w1,
    count(`f_cId`) over w2
from
    `t1`
window w1 as (partition by `f_requestId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding MAXSIZE 100),
       w2 as (partition by `f_uId` order by `eventTime` rows_range between 604800999 preceding and 0s preceding MAXSIZE 100)
```

We can reproduce the issue by only enable unsafe row opt.

```
.config("spark.openmldb.unsaferow.opt", true)
```

**Comment by tobegit3hub** [comment]
There are null data in timestamp column. We can simplify the data with the following SQL.

```
val sql = "SELECT reqId, f_cId, f_requestId, f_uId, eventTime, f_cPubTime FROM t1 ORDER BY f_cPubTime LIMIT 3"
```

```
+-------------------+--------------------+-----+--------------------+--------+-------------------+-------------------+
|count(f_cId)over w2|               reqId|f_cId|         f_requestId|   f_uId|          eventTime|         f_cPubTime|
+-------------------+--------------------+-----+--------------------+--------+-------------------+-------------------+
|                  1|a726969c-cb66-11e...| 4732|583c0a9a45f541477...|13654736|               null|1970-01-01 08:00:00|
|                  1|a851f9c5-cb66-11e...| 4781|583e29857e7b37940...|14447111|               null|1970-01-01 08:00:00|
|                  1|af70c885-cb66-11e...|   14|584b0457c2b491906...|19431489|2016-12-10 08:00:00|2015-11-02 08:00:00|
+-------------------+--------------------+-----+--------------------+--------+-------------------+-------------------+
```

**Comment by tobegit3hub** [comment]
There is a bug for codec when window over window.

```
  def decode(nativeRow1: NativeRow, nativeRow2: NativeRow, row1Size: Int, row2Size: Int, output: Array[Any]): Unit = {
    val sliceIndex = 0
    val rowView = rowViews(sliceIndex)
    val schema = sliceSchemas(sliceIndex)
    var inputRowIndex = 0;

    for (outputColIndex <- 0 until row1Size + row2Size) {

      if (outputColIndex == 0) {
        if (!rowView.Reset(nativeRow1.buf(sliceIndex), nativeRow1.size(sliceIndex))) {
          throw new HybridSeException("Fail to setup row builder, maybe row buf is corrupted")
        }
      } else if (outputColIndex == row1Size) {
        if (!rowView.Reset(nativeRow2.buf(sliceIndex), nativeRow2.size(sliceIndex))) {
          throw new HybridSeException("Fail to setup row builder, maybe row buf is corrupted")
        }
        // Reset the inputRowIndex to get data from row2
        inputRowIndex = 0
      }

      val field = schema(outputColIndex)
      if (rowView.IsNULL(outputColIndex)) {

......
```

The last line of the above code should check null for `inputRowIndex` instead of `outputColIndex` which may get incorrect null value of the row.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix-dihao](https://trello.com/c/NcZTvHzh/16-bugfix-dihao)
