### ISSUE TITLE
Fail to load data with thousands of columns for Spark local mode

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#1911]
Now we can not use load data with thousands of columns for Spark local mode.

The error message is about out of memory of heap.

```
Driver stacktrace:
22/05/31 16:00:32 INFO scheduler.DAGScheduler: Job 1 failed: save at LoadDataPlan.scala:111, took 53.015321 s
22/05/31 16:00:32 ERROR datasources.FileFormatWriter: Aborting job ab5e5ef1-daf1-4f85-8fe7-4a4b43728872.
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 1.0 failed 1 times, most recent failure: Los
t task 0.0 in stage 1.0 (TID 2, 192.168.102.25, executor driver): org.apache.spark.SparkException: Task failed while writing ro
ws.
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.executeTask(FileFormatWriter.scala:291)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.$anonfun$write$15(FileFormatWriter.scala:205)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:127)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.OutOfMemoryError: Java heap space
```

**Comment by tobegit3hub** [comment]
For Spark local mode, we need to set the config of `spark.driver.memory` which is 1g by default.

Just append the following config.

<img width="880" alt="wecom-temp-92229996373a1b5ff7f91233161d329d" src="https://user-images.githubusercontent.com/2715000/171152670-42a704ae-2aa1-42f6-9c9a-7727645efc26.png">

Then restart the taskmanager service.

```
vim conf/taskmanager.properties

./bin/start.sh restart taskmanager
```
