### ISSUE TITLE
Spark Offline mission  with function   top_n_key_count_cate_where() can't run

### ISSUE THREAD

**Issue by LONGZaixiang** [4paradigm/OpenMLDB#2342]
**Bug Description**

Spark Offline mission  with function   top_n_key_count_cate_where() can't run

Log Detail

Driver stacktrace:
org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 5.0 failed 4 times, most recent failure: Lost task 0.3 in stage 5.0 (TID 22, dev-BigDataCluster1, executor 2): com._4paradigm.hybridse.sdk.HybridSeException: Fail to setup row builder, maybe row buf is corrupted
	at com._4paradigm.openmldb.batch.SparkRowCodec.decodeSingle(SparkRowCodec.scala:224)
	at com._4paradigm.openmldb.batch.SparkRowCodec.$anonfun$decode$1(SparkRowCodec.scala:90)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at com._4paradigm.openmldb.batch.SparkRowCodec.decode(SparkRowCodec.scala:89)
	at com._4paradigm.openmldb.batch.window.WindowComputer.compute(WindowComputer.scala:113)
	at com._4paradigm.openmldb.batch.nodes.WindowAggPlan$.$anonfun$windowAggIter$2(WindowAggPlan.scala:548)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at com._4paradigm.openmldb.batch.utils.AutoDestructibleIterator.hasNext(AutoDestructibleIterator.scala:24)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:155)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.failJobAndIndependentStages(DAGScheduler.scala:2023)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:1972)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:1971)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1971)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:950)
	at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:950)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:950)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2203)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2152)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2141)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:752)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2093)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2114)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2133)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:467)
	at org.apache.spark.sql.execution.SparkPlan.executeTake(SparkPlan.scala:420)
	at org.apache.spark.sql.Dataset.$anonfun$isEmpty$1(Dataset.scala:614)
	at org.apache.spark.sql.Dataset.$anonfun$isEmpty$1$adapted(Dataset.scala:613)
	at org.apache.spark.sql.Dataset.$anonfun$withAction$1(Dataset.scala:3617)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$5(SQLExecution.scala:100)
	at org.apache.spark.sql.execution.SQLExecution$.withSQLConfPropagated(SQLExecution.scala:160)
	at org.apache.spark.sql.execution.SQLExecution$.$anonfun$withNewExecutionId$1(SQLExecution.scala:87)
	at org.apache.spark.sql.SparkSession.withActive(SparkSession.scala:797)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:64)
	at org.apache.spark.sql.Dataset.withAction(Dataset.scala:3615)
	at org.apache.spark.sql.Dataset.isEmpty(Dataset.scala:613)
	at com._4paradigm.openmldb.batch.nodes.SelectIntoPlan$.gen(SelectIntoPlan.scala:39)
	at com._4paradigm.openmldb.batch.SparkPlanner.visitNode(SparkPlanner.scala:271)
	at com._4paradigm.openmldb.batch.SparkPlanner.getSparkOutput(SparkPlanner.scala:232)
	at com._4paradigm.openmldb.batch.SparkPlanner.$anonfun$plan$1(SparkPlanner.scala:113)
	at com._4paradigm.openmldb.batch.SparkPlanner.withSQLEngine(SparkPlanner.scala:380)
	at com._4paradigm.openmldb.batch.SparkPlanner.plan(SparkPlanner.scala:83)
	at com._4paradigm.openmldb.batch.api.OpenmldbSession.openmldbSql(OpenmldbSession.scala:169)
	at com._4paradigm.openmldb.batch.api.OpenmldbSession.sql(OpenmldbSession.scala:180)
	at com._4paradigm.openmldb.batchjob.util.OpenmldbJobUtil$.runOpenmldbSql(OpenmldbJobUtil.scala:54)
	at com._4paradigm.openmldb.batchjob.ExportOfflineData$.exportOfflineData(ExportOfflineData.scala:31)
	at com._4paradigm.openmldb.batchjob.ExportOfflineData$.main(ExportOfflineData.scala:26)
	at com._4paradigm.openmldb.batchjob.ExportOfflineData.main(ExportOfflineData.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:728)
Caused by: com._4paradigm.hybridse.sdk.HybridSeException: Fail to setup row builder, maybe row buf is corrupted
	at com._4paradigm.openmldb.batch.SparkRowCodec.decodeSingle(SparkRowCodec.scala:224)
	at com._4paradigm.openmldb.batch.SparkRowCodec.$anonfun$decode$1(SparkRowCodec.scala:90)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
	at com._4paradigm.openmldb.batch.SparkRowCodec.decode(SparkRowCodec.scala:89)
	at com._4paradigm.openmldb.batch.window.WindowComputer.compute(WindowComputer.scala:113)
	at com._4paradigm.openmldb.batch.nodes.WindowAggPlan$.$anonfun$windowAggIter$2(WindowAggPlan.scala:548)
	at scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:484)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:490)
	at com._4paradigm.openmldb.batch.utils.AutoDestructibleIterator.hasNext(AutoDestructibleIterator.scala:24)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage1.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anon$1.hasNext(WholeStageCodegenExec.scala:729)
	at scala.collection.Iterator$$anon$10.hasNext(Iterator.scala:458)
	at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:155)
	at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:59)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:99)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:52)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Expected Behavior**

**Steps to Reproduce**

1.   build table 
    create table userBhvAnalysisOnline(target int, requstId string, logTime timestamp, uWorkFunc string, jWorkFunc string,userId int, jobId int, coId int,  index(key = (jWorkFunc,uWorkFunc),ts=logTime),index( key = coId,  ts=logTime ),index( key = userId,  ts=logTime) );
2.  import data
  1,app_searchjob-1656355840771-08618842-,1656356125269,2965,0106,195881919,136049743,2863836
  1,app_searchjob-1656355840771-08618842-,1656356125269,2965,0106,195881919,136049743,2863836
  1,app_searchjob-1656355840771-08618842-,1656356125269,2965,0106,195881919,136049743,2863836
  0,app_searchjob-1656465735061-55792364-,1656465735139,6732,0106,195455005,137936784,6220238
  0,app_searchjob-1656465735061-55792364-,1656465735139,6732,0106,195455005,137936784,6220238
  1,app_searchjob-1656351611721-07012271-,1656351625149,6905,0106,212729116,140196165,6085043
  1,app_searchjob-1656351611721-07012271-,1656351625149,6905,0106,212729116,140196165,6085043
  1,app_searchjob-1656351611721-07012271-,1656351625149,6905,0106,212729116,140196165,6085043
  0,jobtab_recommend-1656497184187-74320020-,1656497184255,8052,0106,212912570,128651086,3354974
  0,jobtab_recommend-1656497184187-74320020-,1656497184255,8052,0106,212912570,128651086,3354974
  1,app_searchjob-1656385993120-94108061-,1656385999792,8052,0106,211173812,133497954,2204116
  1,app_searchjob-1656385993120-94108061-,1656385999792,8052,0106,211173812,133497954,2204116
  1,app_searchjob-1656385993120-94108061-,1656385999792,8052,0106,211173812,133497954,2204116
  0,app_searchjob-1656462000176-22008439-,1656462000284,0208,0107,42088241, 134663280,2547853
  0,app_searchjob-1656462000176-22008439-,1656462000284,0208,0107,42088241, 134663280,2547853

3.   run  sql  in  offline mode
   SET @@execute_mode='offline';
   select userId,jobId,target,coId ,uWorkFunc,jWorkFunc, count_where(jWorkFunc,target="0") over w,
    count_where(jWorkFunc,target="1") over w ,
    count_where(jWorkFunc,target="2") over w ,
    count_where(coId,target="0") over w2,count_where(coId,target="1") over w2,
    count_where(coId,target="2") over w2,
    top_n_key_count_cate_where(jobId,target="1",jobId,5)  over w3 as topT1,
    top_n_key_count_cate_where(jobId,target="2",jobId,5) over w3 as topT2
    from userBhvAnalysisOnline WINDOW w AS(PARTITION BY uWorkFunc,jWorkFunc ORDER BY logTime ROWS_RANGE BETWEEN 1d PRECEDING AND CURRENT ROW), 
    w2 AS(PARTITION BY coId ORDER BY logTime  ROWS_RANGE BETWEEN 1d PRECEDING AND CURRENT ROW),
    w3 AS(PARTITION BY userId ORDER BY logTime desc ROWS_RANGE BETWEEN 15d PRECEDING AND CURRENT ROW)

4. I have tried running this SQL  without top_n* ,it would run properly .

**Comment by tobegit3hub** [comment]
`top_n_key_count_cate_where` works with the following data for offline.

```
  def main(args: Array[String]): Unit = {

    // Read parquet files
    val spark = SparkSession.builder()
      .master("local")
      .getOrCreate()

    val sess = new OpenmldbSession(spark)

    val schema = StructType(List(
      StructField("value", IntegerType),
      StructField("condition", BooleanType),
      StructField("catagory", StringType)
    ))
    
    val data = Seq(
      Row(0, true, "x"),
      Row(1, true, "y")
    )

    val df = spark.createDataFrame(spark.sparkContext.makeRDD(data), schema)
    sess.registerTable("t1", df)

    val sqlText =
      """
        |select
        | top_n_key_count_cate_where(value, condition, catagory, 2) over w1 as topn
        |from t1
        |window
        | w1 as (partition by `catagory` order by `value` rows_range between 1727 preceding and 0s preceding)
        |""".stripMargin

    val outputDf = sess.sql(sqlText)
    outputDf.show()

    sess.close()
  }
```

**Comment by tobegit3hub** [comment]
The following SQL and data works in my environment.  And we need to import the CSV data like this.

```
load data infile 'file:///Users/tobe/temp/topn_issue/data.csv' into table db1.userBhvAnalysisOnline options(format='csv', header=false, mode='append');
```

And here is the result of the offline query.

<img width="1551" alt="image" src="https://user-images.githubusercontent.com/2715000/185050082-b2bff5ac-eb83-4176-8093-236fda597102.png">

**Comment by tobegit3hub** [comment]
@LONGZaixiang Can you provide the version and more info about this issue?

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug List (0.7)](https://trello.com/c/JVdN9kkX/161-bug-list-07)

**Comment by tobegit3hub** [comment]
Close if we have no more comment.
