### ISSUE TITLE
openmldb-import run error

### ISSUE THREAD

**Issue by zoyopei** [4paradigm/OpenMLDB#2377]
**Bug Description**
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/curator/connection/ConnectionHandlingPolicy
        at org.apache.curator.framework.CuratorFrameworkFactory.builder(CuratorFrameworkFactory.java:82)
        at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:108)
        at org.apache.curator.framework.CuratorFrameworkFactory.newClient(CuratorFrameworkFactory.java:94)
        at com._4paradigm.openmldb.importer.Importer.getTableMetaData(Importer.java:266)
        at com._4paradigm.openmldb.importer.Importer.Load(Importer.java:151)
        at com._4paradigm.openmldb.importer.Importer.main(Importer.java:331)
Caused by: java.lang.ClassNotFoundException: org.apache.curator.connection.ConnectionHandlingPolicy
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by aceforeverd** [comment]
openmldb-import version ? 
I think this problem have been resolved @vagetablechicken ?

**Comment by aceforeverd** [comment]
same as #2188

**Comment by zoyopei** [comment]
v0.6.0，same error in main branch.
Depends on multiple versions of curator.

```
[INFO] com.4paradigm.openmldb:openmldb-import:jar:1.0-SNAPSHOT
[INFO] +- com.4paradigm.openmldb:openmldb-common:jar:0.3.2:compile
[INFO] |  +- org.apache.curator:curator-framework:jar:4.2.0:compile
[INFO] |  \- org.apache.curator:curator-recipes:jar:4.2.0:compile
[INFO] +- org.apache.curator:apache-curator:pom:5.1.0:compile
[INFO] \- org.apache.hadoop:hadoop-common:jar:3.2.4:compile
[INFO]    \- org.apache.curator:curator-client:jar:2.13.0:compile
```

> openmldb-import version ? I think this problem have been resolved @vagetablechicken ?

**Comment by aceforeverd** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug List (0.7)](https://trello.com/c/JVdN9kkX/161-bug-list-07)

**Comment by vagetablechicken** [comment]
I'll test it, maybe exclude them.

set the same curator version
