### ISSUE TITLE
 Failed to import data with longwindow in online sever

### ISSUE THREAD

**Issue by uttinie** [4paradigm/OpenMLDB#2465]
**Bug Description**
version: openmldb 0.6.1
total： 870w
failed at 625w

`W0911 15:58:26.706305 34047 tablet_client.cc:267] fail to send write request for update aggr failed and error code -1
W0911 15:58:26.706326 34047 sql_cluster_router.cc:1198] fail to make a put request to table. tid 9
22/09/11 15:58:26 INFO InsertPreparedStatementImpl: fail to make a put request to table. tid 9
W0911 15:58:26.710826 34042 tablet_client.cc:267] fail to send write request for update aggr failed and error code -1
W0911 15:58:26.710850 34042 sql_cluster_router.cc:1198] fail to make a put request to table. tid 9
22/09/11 15:58:26 INFO InsertPreparedStatementImpl: fail to make a put request to table. tid 9
java.sql.SQLException: insert failed. result code: -1
	at com._4paradigm.openmldb.spark.write.OpenmldbDataWriter.commit(OpenmldbDataWriter.java:134)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:450)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
W0911 15:58:26.734683 34052 tablet_client.cc:267] fail to send write request for update aggr failed and error code -1
W0911 15:58:26.734704 34052 sql_cluster_router.cc:1198] fail to make a put request to table. tid 9
22/09/11 15:58:26 ERROR Utils: Aborting task
java.io.IOException: insert failed. result code: -1
	at com._4paradigm.openmldb.spark.write.OpenmldbDataWriter.commit(OpenmldbDataWriter.java:140)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:450)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
22/09/11 15:58:26 INFO InsertPreparedStatementImpl: fail to make a put request to table. tid 9
22/09/11 15:58:26 ERROR DataWritingSparkTask: Aborting commit for partition 8 (task 310, attempt 0, stage 6.0)
22/09/11 15:58:26 ERROR DataWritingSparkTask: Aborted commit for partition 8 (task 310, attempt 0, stage 6.0)
22/09/11 15:58:26 ERROR Executor: Exception in task 8.0 in stage 6.0 (TID 310)
java.io.IOException: insert failed. result code: -1
	at com._4paradigm.openmldb.spark.write.OpenmldbDataWriter.commit(OpenmldbDataWriter.java:140)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:450)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
22/09/11 15:58:26 INFO TaskSetManager: Starting task 32.0 in stage 6.0 (TID 334, gz5-tysearch-bms-Indexer-97-152-110, executor driver, partition 32, PROCESS_LOCAL, 8066 bytes)
22/09/11 15:58:26 INFO Executor: Running task 32.0 in stage 6.0 (TID 334)
22/09/11 15:58:26 WARN TaskSetManager: Lost task 8.0 in stage 6.0 (TID 310, gz5-tysearch-bms-Indexer-97-152-110, executor driver): java.io.IOException: insert failed. result code: -1
	at com._4paradigm.openmldb.spark.write.OpenmldbDataWriter.commit(OpenmldbDataWriter.java:140)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.$anonfun$run$7(WriteToDataSourceV2Exec.scala:450)
	at org.apache.spark.util.Utils$.tryWithSafeFinallyAndFailureCallbacks(Utils.scala:1411)
	at org.apache.spark.sql.execution.datasources.v2.DataWritingSparkTask$.run(WriteToDataSourceV2Exec.scala:477)
	at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.$anonfun$writeWithV2$2(WriteToDataSourceV2Exec.scala:385)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:127)
	at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:444)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1377)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:447)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

22/09/11 15:58:26 ERROR TaskSetManager: Task 8 in stage 6.0 failed 1 times; aborting job
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@753: Client environment:zookeeper.version=zookeeper C client 3.4.14
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@757: Client environment:host.name=gz5-tysearch-bms-Indexer-97-152-110
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@764: Client environment:os.name=Linux
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@765: Client environment:os.arch=3.10.0-514.44.5.10.h296.x86_64
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@766: Client environment:os.version=#1 SMP Wed Dec 16 09:21:23 UTC 2020
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@774: Client environment:user.name=root
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@782: Client environment:user.home=/home/tysearch
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@log_env@794: Client environment:user.dir=/opt/company/data/OnlineLearning/openmldb-taskmanager-0.6.1/taskmanager/bin
2022-09-11 15:58:26,760:31806(0x7fa8f20c6700):ZOO_INFO@zookeeper_init@827: Initiating client connection, host=10.97.152.110:22181,10.97.152.190:22181,10.97.152.199:22181 sessionTimeout=10000 watcher=0x7fa93c260380 sessionId=0 sessionPasswd=<null> context=0x7fa4409185a0 flags=0
2022-09-11 15:58:26,760:31806(0x7fa705ffb700):ZOO_INFO@check_events@1764: initiated connection to server [10.97.152.199:22181]
2022-09-11 15:58:26,762:31806(0x7fa705ffb700):ZOO_INFO@check_events@1811: session establishment complete on server [10.97.152.199:22181], sessionId=0x305ea552d120029, negotiated timeout=10000
I0911 15:58:26.762729 43700 zk_client.cc:558] zookeeper event with type -1, state 3, path 
I0911 15:58:26.762773 43700 zk_client.cc:573] connect success
I0911 15:58:26.762791 34020 db_sdk.cc:212] init zk client with zk cluster 10.97.152.110:22181,10.97.152.190:22181,10.97.152.199:22181 , zk path /openmldb_cluster,session timeout 10000 and session id 1
22/09/11 15:58:26 INFO TaskSchedulerImpl: Cancelling stage 6
22/09/11 15:58:26 INFO TaskSchedulerImpl: Killing all running tasks in stage 6: Stage cancelled
W0911 15:58:26.764199 34047 tablet_client.cc:267] fail to send write request for update aggr failed and error code -1`

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by uttinie** [comment]
E0911 15:55:46.046561 55626 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.046623 55626 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A9^B]
E0911 15:55:46.297758 55642 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.297807 55642 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A6^B]
E0911 15:55:46.379712 55619 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.379756 55619 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A7^B]
E0911 15:55:46.544603 55627 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.544648 55627 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^AÑ^A]
E0911 15:55:46.557687 55625 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.557723 55625 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^AÖ^A]
E0911 15:55:46.562650 55619 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.562678 55619 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A7^B]
E0911 15:55:46.777585 55632 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.777643 55632 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A^R^B]
W0911 15:55:46.841132 55642 replicate_node.cc:264] fail to get record: End of file. tid 10 pid 7
W0911 15:55:46.841138 55624 replicate_node.cc:264] fail to get record: End of file. tid 10 pid 7
E0911 15:55:46.863955 55619 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.864001 55619 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A^G^B]
E0911 15:55:46.922381 55636 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.922425 55636 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A×^A]
E0911 15:55:46.930692 55636 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:46.930727 55636 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^AÏ^A]
E0911 15:55:47.011812 55627 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:47.011857 55627 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^A     ^B]
E0911 15:55:47.050465 55641 aggregator.cc:168] logical error: current offset is smaller than binlog offset
W0911 15:55:47.050523 55641 tablet_impl.cc:4169] update aggr failed. tid[9] pid[1] index[2] key[12.0.6.300|12.0] value[^A^AÓ^A]

**Comment by zhanghaohit** [comment]
There is a potential bug for the checking of `binlog offset`. If there are multiple threads doing `Put` at the same time, an entry with a bigger offset may call `UpdateAggrs` earlier than the entry with a smaller offset.

https://github.com/4paradigm/OpenMLDB/blob/831658edce694b381d343058e1899452d4a7dca0/src/storage/aggregator.cc#L164
