### ISSUE TITLE
tablet keeps CPU 160%

### ISSUE THREAD

**Issue by uttinie** [4paradigm/OpenMLDB#2483]
**Bug Description**
version：0.6.1
(gdb) bt
#0  0x00007f155879f5dd in nanosleep () from /lib64/libc.so.6
#1  0x00007f15587cfde4 in usleep () from /lib64/libc.so.6
#2  0x0000000001bcd137 in bthread_usleep (microseconds=microseconds@entry=1000000) at /__w/hybridsql-asserts/hybridsql-asserts/deps/build/src/brpc/src/bthread/bthread.cpp:363
#3  0x0000000001cb0afa in brpc::Server::RunUntilAskedToQuit (this=this@entry=0x7ffe42314240) at /__w/hybridsql-asserts/hybridsql-asserts/deps/build/src/brpc/src/brpc/server.cpp:1700
#4  0x00000000005ae7d7 in StartTablet() () at /__w/OpenMLDB/OpenMLDB/src/cmd/openmldb.cc:268
#5  0x000000000051c5c7 in main (argc=<optimized out>, argv=<optimized out>) at /__w/OpenMLDB/OpenMLDB/src/cmd/openmldb.cc:3945
(gdb) quit
A debugging session is active.

	Inferior 1 [process 26558] will be detached.

Quit anyway? (y or n) y
Detaching from program: /opt/huawei/data/OnlineLearning/openmldb-tablet-0.6.1/bin/openmldb, process 26558

重复持续打印以下日志
W0916 17:10:01.019234 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019245 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019256 26583 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019268 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019277 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019289 26574 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019299 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019307 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019318 26583 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019330 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019340 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019351 26574 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019362 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019372 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019382 26583 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019392 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019402 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019413 26574 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019424 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019435 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019445 26583 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019455 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019466 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019477 26574 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019488 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019500 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019510 26583 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019521 26574 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019532 26583 log_reader.cc:529] no log part matched! start_offset[0]
W0916 17:10:01.019542 26574 log_reader.cc:477] fail to roll read log
W0916 17:10:01.019552 26583 log_reader.cc:529] no log part matched! start_offset[0]

**Expected Behavior**

**Steps to Reproduce**

1. 
2. 
3. 
4.

**Comment by uttinie** [comment]
[showtable.txt](https://github.com/4paradigm/OpenMLDB/files/9582969/showtable.txt)
