### ISSUE TITLE
Support get_columns and parse protobuf object for Python SDK

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#3180]
Here is the code to test.

```
import sqlalchemy as db
from sqlalchemy import inspect

zk_cluster = "127.0.0.1:2181"
zk_path = "/openmldb"

engine = db.create_engine(f'openmldb:///db1?zk={zk_cluster}&zkPath={zk_path}')
connection = engine.connect()

insp = inspect(engine)
print(insp.get_table_names())

columns = insp.get_columns('employees')

for column in columns:
    print(column)
```

We may add the code in `openmldb_dialect.py`.

```
    def get_columns(self, connection, table_name, schema=None, **kw):
        """
        columns_info = [
            {
                'name': 'name',
                'type': sqlalchemy.String(),
                'nullable': False,
                'default': None,
                'primary_key': False,
                'autoincrement': False,
                'comment': 'Unique identifier for the row'
            }
        ]
        return columns_info
        """
        raise NotImplementedError()
```

**Comment by tobegit3hub** [comment]
Here is the code to warp C api to get protobuf TableInfo.

```
--- a/python/openmldb_sdk/openmldb/dbapi/dbapi.py
+++ b/python/openmldb_sdk/openmldb/dbapi/dbapi.py
@@ -417,6 +417,9 @@ class Cursor(object):
     def get_tables(self, db):
         return self.connection._sdk.getTables(db)

+    def get_table_info(self, db, table):
+        return self.connection._sdk.getTableInfo(db, table)
+
     def get_all_tables(self):
         return self.connection._sdk.getAllTables()

diff --git a/python/openmldb_sdk/openmldb/sdk/sdk.py b/python/openmldb_sdk/openmldb/sdk/sdk.py
index bc8454039..05dcbb836 100644
--- a/python/openmldb_sdk/openmldb/sdk/sdk.py
+++ b/python/openmldb_sdk/openmldb/sdk/sdk.py
@@ -120,6 +120,12 @@ class OpenMLDBSdk(object):
             raise Exception("please init sdk first")
         return self.sdk.GetTableNames(db)

+    def getTableInfo(self, db, table):
+        if not self.sdk:
+            raise Exception("please init sdk first")
+        return self.sdk.GetTableInfo(db, table)
+
     def getAllTables(self):
         if not self.sdk:
             raise Exception("please init sdk first")
```

But we can not call API which may return the share pointer of protobuf TableInfo object. Here is the error message.

```
Traceback (most recent call last):
  File "/Users/tobe/code/4pd/OpenMLDB/python/openmldb_sdk/tobe/./use_openmldb_sqlalchemy.py", line 15, in <module>
    columns = insp.get_columns('employees')
  File "/Users/tobe/code/4pd/OpenMLDB/python/openmldb_sdk/venv/lib/python3.9/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/Users/tobe/code/4pd/OpenMLDB/python/openmldb_sdk/openmldb/sqlalchemy_openmldb/openmldb_dialect.py", line 149, in get_columns
    table_info = table_infos[0]
TypeError: 'SwigPyObject' object is not subscriptable
swig/python detected a memory leak of type '::openmldb::nameserver::TableInfo *', no destructor found.
2023-03-31 15:36:08,931:58842(0x7ff855e7f680):ZOO_INFO@zookeeper_close@2564: Closing zookeeper sessionId=0x1000cacd0970038 to [127.0.0.1:2181]
```

The `sql_router_sdk.i` only handle the generated code in Java.

```
// Enable protobuf interfaces
%include "swig_library/java/protobuf.i"
%protobuf(openmldb::nameserver::TableInfo, com._4paradigm.openmldb.proto.NS.TableInfo);
#endif
```
