### ISSUE TITLE
pure virtual method called

### ISSUE THREAD

**Issue by vagetablechicken** [4paradigm/OpenMLDB#3416]
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fa21d102537 in __GI_abort () at abort.c:79
#2  0x00007fa21d4ac7ec in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fa21d4b7966 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007fa21d4b79d1 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007fa21d4b869f in __cxa_pure_virtual () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x0000557144278b05 in brpc::Controller::OnVersionedRPCReturned (this=0x7fa1f0053fd0, info=..., new_bthread=<optimized out>, saved_error=<optimized out>) at /home/ace/deps/build/src/brpc/src/brpc/controller.cpp:637
#7  0x000055714427929e in brpc::Controller::HandleSendFailed (this=0x7fa1f0053fd0) at /home/ace/deps/build/src/brpc/src/brpc/controller.cpp:1007
#8  0x0000557144277df8 in brpc::Controller::IssueRPC (this=0x7fa1f0053fd0, start_realtime_us=<optimized out>) at /home/ace/deps/build/src/brpc/src/brpc/controller.cpp:1159
#9  0x0000557144270832 in brpc::Channel::CallMethod (this=0x55714827e940, method=0x5571481e5b60, controller_base=0x7fa1f0053fd0, request=0x7fa1f0054330, response=0x7fa1f00543b0, done=0x0) at /home/ace/deps/build/src/brpc/src/brpc/channel.cpp:576
#10 0x00005571432939c4 in openmldb::api::TabletServer_Stub::GetTaskStatus (this=0x55714b60b320, controller=0x7fa1f0053fd0, request=0x7fa1f0054330, response=0x7fa1f00543b0, done=0x0) at src/proto/tablet.pb.cc:46385
#11 0x0000557143ba59cf in openmldb::RpcClient<openmldb::api::TabletServer_Stub>::SendRequest<openmldb::api::TaskStatusRequest, openmldb::api::TaskStatusResponse, google::protobuf::Closure> (this=0x557148943958, func=&virtual table offset 272, request=0x7fa1f0054330, response=0x7fa1f00543b0, rpc_timeout=20000, retry_times=1) at ../src/rpc/rpc_client.h:140
#12 0x0000557143b912c7 in openmldb::client::TabletClient::GetTaskStatus (this=0x557148943910, response=...) at ../src/client/tablet_client.cc:457
#13 0x00005571435969a8 in openmldb::nameserver::NameServerImpl::UpdateTaskStatus (this=0x557147d1ea00, is_recover_op=false) at ../src/nameserver/name_server_impl.cc:1548
#14 0x0000557143773b50 in boost::_mfi::mf1<int, openmldb::nameserver::NameServerImpl, bool>::operator() (this=0x55714ba61de0, p=0x557147d1ea00, a1=false) at /home/ace/deps/usr/include/boost/bind/mem_fn_template.hpp:165
#15 0x000055714375d5bd in boost::_bi::list2<boost::_bi::value<openmldb::nameserver::NameServerImpl*>, boost::_bi::value<bool> >::operator()<int, boost::_mfi::mf1<int, openmldb::nameserver::NameServerImpl, bool>, boost::_bi::list0> (this=0x55714ba61df0, f=..., a=...) at /home/ace/deps/usr/include/boost/bind/bind.hpp:309
#16 0x000055714374708f in boost::_bi::bind_t<int, boost::_mfi::mf1<int, openmldb::nameserver::NameServerImpl, bool>, boost::_bi::list2<boost::_bi::value<openmldb::nameserver::NameServerImpl*>, boost::_bi::value<bool> > >::operator() (this=0x55714ba61de0) at /home/ace/deps/usr/include/boost/bind/bind.hpp:1294
#17 0x000055714372be1f in boost::detail::function::void_function_obj_invoker0<boost::_bi::bind_t<int, boost::_mfi::mf1<int, openmldb::nameserver::NameServerImpl, bool>, boost::_bi::list2<boost::_bi::value<openmldb::nameserver::NameServerImpl*>, boost::_bi::value<bool> > >, void>::invoke (function_obj_ptr=...) at /home/ace/deps/usr/include/boost/function/function_template.hpp:158
#18 0x000055714352680e in boost::function0<void>::operator() (this=0x7fa1f0054770) at /home/ace/deps/usr/include/boost/function/function_template.hpp:763
#19 0x0000557143519eb6 in baidu::common::ThreadPool::ThreadProc (this=0x557147d1eeb8) at /home/ace/deps/usr/include/common/thread_pool.h:212
#20 0x0000557143519881 in baidu::common::ThreadPool::ThreadWrapper (arg=0x557147d1eeb8) at /home/ace/deps/usr/include/common/thread_pool.h:183
#21 0x00007fa21d632ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#22 0x00007fa21d1dba2f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```
```
pure virtual method called
terminate called without an active exception
Aborted (core dumped)
```
In some cases, we may get error like this, in ut single_tablet_test/sql_cmd_test...
Core on pool task UpdateTableInfo, when ~NameServerImpl, and it's called by brpc::Server::Stop(delete service). When NameserverImpl dtor, threadpool still running, and may run tasks after threadpool.Stop(it's showed in log, wierd, may be misunderstood). Anyway, if still has running task UpdateTableInfo when dtor, it'll  to send rpc to tablets, and core here.

The better way is, don't let brpc server just delete NameServerImpl, we should add a Stop func for NameServerImpl, to stop all inner thread pool, then stop brpc server.

**Comment by vagetablechicken** [comment]
fixed
