### ISSUE TITLE
zookeeper-3.4.14 client throw "Unable to canonicalize address localhost/<unresolved>:7181 because it's not resolvable" when using jdk 18.0.2.1

### ISSUE THREAD

**Issue by yangwucheng** [4paradigm/OpenMLDB#3766]
**Bug Description**
jdk: 
```
java version "18.0.2.1" 2022-08-18
Java(TM) SE Runtime Environment (build 18.0.2.1+1-1)
Java HotSpot(TM) 64-Bit Server VM (build 18.0.2.1+1-1, mixed mode, sharing)
```

zookeeper config:
```
# The number of milliseconds of each tick
tickTime=2000
# The number of ticks that the initial 
# synchronization phase can take
initLimit=10
# The number of ticks that can pass between
# sending a request and getting an acknowledgement
syncLimit=5
# the directory where the snapshot is stored.
# do not use /tmp for storage, /tmp here is just
# example sakes.
dataDir=./data
# the port at which the clients will connect
clientPort=7181
# the maximum number of client connections.
# increase this if you need to handle more clients
#maxClientCnxns=60
#
# Be sure to read the maintenance section of the
# administrator guide before turning on autopurge.
#
# http://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_maintenance
#
# The number of snapshots to retain in dataDir
#autopurge.snapRetainCount=3
# Purge task interval in hours
# Set to "0" to disable auto purge feature
#autopurge.purgeInterval=1
```

cmd: `bash bin/zkCli.sh -server localhost:7181`

exceptions:
```log
2024-02-21 12:00:54,088 [myid:] - INFO  [main:ZooKeeper@442] - Initiating client connection, connectString=localhost:7181 sessionTimeout=30000 watcher=org.apache.zookeeper.ZooKeeperMain$MyWatcher@3c679bde
Welcome to ZooKeeper!
JLine support is enabled
[zk: localhost:7181(CONNECTING) 0] 2024-02-21 12:00:54,206 [myid:] - WARN  [main-SendThread(localhost:7181):ClientCnxn$SendThread@1164] - Session 0x0 for server localhost/<unresolved>:7181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address localhost/<unresolved>:7181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
2024-02-21 12:00:55,317 [myid:] - WARN  [main-SendThread(localhost:7181):ClientCnxn$SendThread@1164] - Session 0x0 for server localhost/<unresolved>:7181, unexpected error, closing socket connection and attempting reconnect
java.lang.IllegalArgumentException: Unable to canonicalize address localhost/<unresolved>:7181 because it's not resolvable
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:65)
	at org.apache.zookeeper.SaslServerPrincipal.getServerPrincipal(SaslServerPrincipal.java:41)
	at org.apache.zookeeper.ClientCnxn$SendThread.startConnect(ClientCnxn.java:1001)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1060)
```

**Expected Behavior**
update docs, clarify compatible jdk versions

**Relation Case**

**Steps to Reproduce**

1. `bash bin/zkServer.sh start`
2. `bash bin/zkCli.sh -server localhost:7181`

**Comment by aceforeverd** [comment]
https://github.com/apache/kyuubi/issues/1941
https://issues.apache.org/jira/browse/ZOOKEEPER-3779

**Comment by vagetablechicken** [comment]
So jre >= 14 will failed, and we've test it works fine on jre 1.8 and 11, so <=11 is recommended?

**Comment by vagetablechicken** [comment]
Update, the error is zkCli, not the server, haven't seen server error in high java version
