### ISSUE TITLE
Bug: Integration-test support expectProvider

### ISSUE THREAD

**Issue by jingchen2222** [4paradigm/OpenMLDB#546]
Issue tracker is **ONLY** used for reporting bugs. New features should be discussed on our discussion

Recently, SqlCase has been modified by adding `expectProvider`.  I come across errors when parsing SQLCase YAML in java-sdk-test.

## Expected Behavior

Success parse expectProvider.

## Current Behavior

Fail to parse yaml case like: 
```yaml
  - id: in_predicate_type_conversion
    desc: type conversion occurred between lhs and in_list
    mode: hybridse-only
    sql: |
      SELECT {0}.id, {0}.name, {0}.code, {1}.score FROM {0} LAST JOIN {1} ORDER BY {1}.std_ts
      ON {0}.id = {1}.id AND {0}.id d[0] ('1', 3.0);
    inputs:
      - columns: [ "id bigint", "name string", "code string", "ctime timestamp", "cdate date" ]
        indexs: [ "index1:id:ctime" ]
        rows:
          - [1, Lucy,  A, 1609459201000, 2021-1-1]
          - [2, Zoey,  B, 1633265330000, 2021-10-3]
      - columns: [ "id bigint", "std_ts bigint", "score int" ]
        indexs: ["index1:id:std_ts"]
        rows:
          - [1, 1609459201000, 10]
          - [2, 1609459202000, 100]
          - [3, 1609459203000, 20]
          - [4, 1609459204000, 30]
          - [5, 1609459205000, 50]
    dataProvider:
      - ["in", "not in"]
    expect:
      columns: ["id:bigint", "name:string", "code:string", "score:int"]
    expectProvider:
      - rows:
          - [1, Lucy, A, 10]
          - [2, Zoey, B, NULL]
      - rows:
          - [1, Lucy, A, NULL]
          - [2, Zoey, B, 100]
```

```
...
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@753: Client environment:zookeeper.version=zookeeper C client 3.4.14
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@757: Client environment:host.name=Chenjings-MacBook-Pro.local
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@764: Client environment:os.name=Darwin
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@765: Client environment:os.arch=19.6.0
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@766: Client environment:os.version=Darwin Kernel Version 19.6.0: Tue Jun 22 19:49:55 PDT 2021; root:xnu-6153.141.35~1/RELEASE_X86_64
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@774: Client environment:user.name=root
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@782: Client environment:user.home=/Users/chenjing
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@log_env@794: Client environment:user.dir=/Users/chenjing/work/chenjing/OpenMLDB/test/integration-test/openmldb-test-java/openmldb-sdk-test
2021-10-19 11:38:15,774:76969(0x700003002000):ZOO_INFO@zookeeper_init@827: Initiating client connection, host=127.0.0.1:6181 sessionTimeout=1000000 watcher=0x132741e60 sessionId=0 sessionPasswd=<null> context=0x7fbb98240000 flags=0
2021-10-19 11:38:15,775:76969(0x7000053f4000):ZOO_INFO@check_events@1764: initiated connection to server [127.0.0.1:6181]
2021-10-19 11:38:15,776:76969(0x7000053f4000):ZOO_INFO@check_events@1811: session establishment complete on server [127.0.0.1:6181], sessionId=0x1004d061cd80025, negotiated timeout=40000
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1019 11:38:15.777194 88567808 zk_client.cc:540] zookeeper event with type -1, state 3, path 
I1019 11:38:15.777482 88567808 zk_client.cc:555] connect success
I1019 11:38:15.777503 50339840 db_sdk.cc:73] init zk client with zk cluster 127.0.0.1:6181 , zk path /onebox,session timeout 1000000 and session id 1
I1019 11:38:15.790724 50339840 client_manager.cc:471] add client. name 127.0.0.1:9520, endpoint 
I1019 11:38:15.790743 50339840 client_manager.cc:471] add client. name 127.0.0.1:9521, endpoint 
I1019 11:38:15.790751 50339840 client_manager.cc:471] add client. name 127.0.0.1:9522, endpoint 
I1019 11:38:15.799312 50339840 db_sdk.cc:88] start to watch table notify

Cannot create property=cases for JavaBean=FesqlDataProvider()
 in 'reader', line 15, column 1:
    db: test_zw
    ^
Cannot create property=expectProvider for JavaBean=SQLCase(level=0, id=in_predicate_type_conversion, desc=type conversion occurred between lhs and in_list, mode=hybridse-only, db=null, sql=SELECT auto_OceSVIht.id, auto_OceSVIht.name, auto_OceSVIht.code, auto_niXbHvXg.score FROM auto_OceSVIht LAST JOIN auto_niXbHvXg ORDER BY auto_niXbHvXg.std_ts
ON auto_OceSVIht.id = auto_niXbHvXg.id AND auto_OceSVIht.id d[0] ('1', 3.0);
, dataProvider=[[in, not in]], sqls=null, standard_sql=false, standard_sql_compatible=false, tags=null, common_column_indices=null, batch_plan=null, request_plan=null, cluster_request_plan=null, inputs=[InputDesc(resource=null), InputDesc(resource=null)], batch_request=null, expect=ExpectDesc(order=null, count=-1, success=true, options=null), spName=auto_itCGNYza, unequalExpect=null, sqlDialect=null, parameters=null, expectProvider=null)
 in 'reader', line 498, column 5:
      - id: in_predicate_type_conversion
        ^
No suitable constructor with 2 arguments found for interface java.util.Map
 in 'reader', line 523, column 7:
          - rows:
          ^

 in 'reader', line 19, column 3:
      - id: 0
      ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:292)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:472)
	at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:466)
	at com._4paradigm.openmldb.java_sdk_test.entity.FesqlDataProvider.dataProviderGenerator(FesqlDataProvider.java:44)
	at com._4paradigm.openmldb.java_sdk_test.entity.FesqlDataProviderList.dataProviderGenerator(FesqlDataProviderList.java:75)
	at com._4paradigm.openmldb.java_sdk_test.common.BaseTest.getCaseByYaml(BaseTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:74)
	at org.testng.internal.MethodInvocationHelper.invokeMethodNoCheckedException(MethodInvocationHelper.java:45)
	at org.testng.internal.MethodInvocationHelper.invokeDataProvider(MethodInvocationHelper.java:131)
	at org.testng.internal.Parameters.handleParameters(Parameters.java:706)
	at org.testng.internal.ParameterHandler.handleParameters(ParameterHandler.java:49)
	at org.testng.internal.ParameterHandler.createParameters(ParameterHandler.java:37)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:924)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:648)
	at org.testng.TestRunner.run(TestRunner.java:505)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
	at org.testng.SuiteRunner.run(SuiteRunner.java:364)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: Cannot create property=expectProvider for JavaBean=SQLCase(level=0, id=in_predicate_type_conversion, desc=type conversion occurred between lhs and in_list, mode=hybridse-only, db=null, sql=SELECT auto_OceSVIht.id, auto_OceSVIht.name, auto_OceSVIht.code, auto_niXbHvXg.score FROM auto_OceSVIht LAST JOIN auto_niXbHvXg ORDER BY auto_niXbHvXg.std_ts
ON auto_OceSVIht.id = auto_niXbHvXg.id AND auto_OceSVIht.id d[0] ('1', 3.0);
, dataProvider=[[in, not in]], sqls=null, standard_sql=false, standard_sql_compatible=false, tags=null, common_column_indices=null, batch_plan=null, request_plan=null, cluster_request_plan=null, inputs=[InputDesc(resource=null), InputDesc(resource=null)], batch_request=null, expect=ExpectDesc(order=null, count=-1, success=true, options=null), spName=auto_itCGNYza, unequalExpect=null, sqlDialect=null, parameters=null, expectProvider=null)
 in 'reader', line 498, column 5:
      - id: in_predicate_type_conversion
        ^
No suitable constructor with 2 arguments found for interface java.util.Map
 in 'reader', line 523, column 7:
          - rows:
          ^

	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:292)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.construct(Constructor.java:171)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequenceStep2(BaseConstructor.java:390)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructSequence(BaseConstructor.java:374)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:538)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:269)
	... 39 more
Caused by: org.yaml.snakeyaml.error.YAMLException: No suitable constructor with 2 arguments found for interface java.util.Map
	at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:606)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:230)
	at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
	at org.yaml.snakeyaml.constructor.Constructor$ConstructMapping.constructJavaBean2ndStep(Constructor.java:269)
	... 48 more


java.lang.AssertionError: fail to run fesql test with FAIL DATA PROVIDER SQLCase: check yaml case
...
```
## Possible Solution

There are two options:
```
  expectProvider:
    - rows:
        - [1, Lucy, A, 10]
        - [2, Zoey, B, NULL]
    - rows:
        - [1, Lucy, A, NULL]
        - [2, Zoey, B, 100]
```
Option 1: Support above `expectProvider`. @wuyou10206 
Make sure integration-test can read and parse the new case format.
Option 2: Do not support the above style.  @aceforeverd 
Remove support above `expectProvider` style in sql_case.cc. 

The principle is make sure c++ sql_case and java SQLCase have the same behaviours.

If you have any problems with the new YAML case, please contact with @aceforeverd and @jingchen2222 

## Steps to Reproduce

1. 
2.
3.
4.

**Comment by jingchen2222** [comment]
Please add expectProvider parse UT @wuyou10206

**Comment by jingchen2222** [comment]
Now I simply modify the yaml case. Use the expectProvider map style. https://github.com/4paradigm/OpenMLDB/pull/545/commits/b3cd638c2734e7eefdaae09303605c5d957da610
@aceforeverd @wuyou10206

**Comment by aceforeverd** [comment]
closable ? @jingchen2222

**Comment by aceforeverd** [comment]
not planned
