### ISSUE TITLE
Fail when submitting openmldb-batch in Yarn 

### ISSUE THREAD

**Issue by tobegit3hub** [4paradigm/OpenMLDB#970]
It throws exception about protobuf when using openmldb-batch in yarn-cluster.

**Comment by tobegit3hub** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [bugfix tracking](https://trello.com/c/wEQ9HW0k/25-bugfix-tracking)

**Comment by tobegit3hub** [comment]
Here is the error message.

```
21/12/28 17:17:23 ERROR yarn.ApplicationMaster: Uncaught exception: 
java.lang.ClassCastException: org.apache.hadoop.yarn.proto.YarnServiceProtos$RegisterApplicationMasterRequestProto cannot be cast to shade.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:226)
	at com.sun.proxy.$Proxy15.registerApplicationMaster(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationMasterProtocolPBClientImpl.registerApplicationMaster(ApplicationMasterProtocolPBClientImpl.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy16.registerApplicationMaster(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:223)
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:214)
	at org.apache.spark.deploy.yarn.YarnRMClient.register(YarnRMClient.scala:71)
	at org.apache.spark.deploy.yarn.ApplicationMaster.registerAM(ApplicationMaster.scala:428)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:507)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:264)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:890)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:889)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:889)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)
21/12/28 17:17:23 INFO yarn.ApplicationMaster: Final app status: FAILED, exitCode: 13, (reason: Uncaught exception: java.lang.ClassCastException: org.apache.hadoop.yarn.proto.YarnServiceProtos$RegisterApplicationMasterRequestProto cannot be cast to shade.protobuf.Message
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:226)
	at com.sun.proxy.$Proxy15.registerApplicationMaster(Unknown Source)
	at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationMasterProtocolPBClientImpl.registerApplicationMaster(ApplicationMasterProtocolPBClientImpl.java:107)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:191)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at com.sun.proxy.$Proxy16.registerApplicationMaster(Unknown Source)
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:223)
	at org.apache.hadoop.yarn.client.api.impl.AMRMClientImpl.registerApplicationMaster(AMRMClientImpl.java:214)
	at org.apache.spark.deploy.yarn.YarnRMClient.register(YarnRMClient.scala:71)
	at org.apache.spark.deploy.yarn.ApplicationMaster.registerAM(ApplicationMaster.scala:428)
	at org.apache.spark.deploy.yarn.ApplicationMaster.runDriver(ApplicationMaster.scala:507)
	at org.apache.spark.deploy.yarn.ApplicationMaster.run(ApplicationMaster.scala:264)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:890)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$3.run(ApplicationMaster.scala:889)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1746)
	at org.apache.spark.deploy.yarn.ApplicationMaster$.main(ApplicationMaster.scala:889)
	at org.apache.spark.deploy.yarn.ApplicationMaster.main(ApplicationMaster.scala)`
```

The reason may be the conflict of protobuf jars from openmldb and yarn cluster. We should exclude the protobuf and hadoop-common in `openmldb-batch` first.

**Comment by tobegit3hub** [comment]
There are some issues to make spark yarn-cluster jobs fail.

* Resolve protobuf conflict issue https://github.com/4paradigm/OpenMLDB/pull/987
* Resolve brpc error code with Chinese charset in Linux https://github.com/4paradigm/OpenMLDB/pull/991
* Resolve init llvm in executors for yarn-cluster mode https://github.com/4paradigm/OpenMLDB/pull/994

**Comment by tobegit3hub** [comment]
We have the issue after resolving the protobuf conflict error.  Get the error message "fail to init jit let" and core in executors. 

<img width="1520" alt="Screen Shot 2021-12-29 at 5 13 05 PM" src="https://user-images.githubusercontent.com/2715000/147727828-efee054b-2827-45d5-a1dd-2b336aa79b74.png">

![image](https://user-images.githubusercontent.com/2715000/147727928-c6519ecb-11be-4b57-b7e1-076960d470ba.png)

It is the issue of initialization of llvm which need to be initialized in driver and executor.
